---
- hosts: windows
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: cloud.internal
      domain_admin_user: admin@alterdata.cloud
      domain_admin_password: ***
      domain_ou_path:
      state: domain
    register: domain_state

  - win_reboot:
        state: reboot
