---
- hosts: all
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: cloud.internal
      domain_admin_user: gustavosouza.infra@cloud.internal
      domain_admin_password: Gustavo@29
      domain_ou_path:
      state: domain
    register: domain_state

  - win_reboot:
        state: restart

